### ISSUE TITLE
The simulation experiments

### ISSUE THREAD

**Issue by MuziYT** [agimus-project/colmpc#19]
Hi,
I read your paper "Model predictive control under hard collision avoidance constraints for a robotic arm" . I have several questions.
1. What I understand is that the USQP comparison method is solved by mini-solvers with soft constraint, is it right?
2. Did you compare the computation time between the CSQP and FDDP?

I would be very grateful if you can help me. I look forward to your reply.

**Comment by ArthurH91** [comment]
Hi! First of all, thank you for your interest in my research! 

> What I understand is that the USQP comparison method is solved by mini-solvers with soft constraint, is it right?

Initially, I divided the USQP into FDDP from crocoddyl and uSQP (unconstrained SQP) from mim solver and solved it using soft constraints. However, the solution was exactly the same. Which makes sense because these solvers are supposed to find the locally optimal solution. 

> Did you compare the computation time between the CSQP and FDDP?

That's a good question.
Without constraints, so with uSQP and FDDP, it takes the same time to solve the same optimal control problem (OCP). 
However when you add hard constraints, the OCP more complex and thus, takes more time to get solved. 

Hope it answered your questions :)

**Comment by MuziYT** [comment]
Thank you very much，your research really help me！



---- Replied Message ----
| From | Arthur ***@***.***> |
| Date | 07/12/2024 23:08 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [agimus-project/colmpc] The simulation experiments (Issue #19) |

Hi! First of all, thank you for your interest in my research!

What I understand is that the USQP comparison method is solved by mini-solvers with soft constraint, is it right?

Initially, I divided the USQP into FDDP from crocoddyl and uSQP (unconstrained SQP) from mim solver and solved it using soft constraints. However, the solution was exactly the same. Which makes sense because these solvers are supposed to find the locally optimal solution.

Did you compare the computation time between the CSQP and FDDP?

That's a good question.
Without constraints, so with uSQP and FDDP, it takes the same time to solve the same optimal control problem (OCP).
However when you add hard constraints, the OCP more complex and thus, takes more time to get solved.

Hope it answered your questions :)

**Comment by ArthurH91** [comment]
I'm very glad ! 
You can contact me on my email or on LinkedIn if you have any other questions :)

**Comment by MuziYT** [comment]
OK，thanks again！I will follow your LinkedIn.



---- Replied Message ----
| From | Arthur ***@***.***> |
| Date | 07/12/2024 23:25 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [agimus-project/colmpc] The simulation experiments (Issue #19) |

I'm very glad !
You can contact me on my email or on LinkedIn if you have any other questions :)
